[[manager.prepend_keymap]]
on = ["<C-d>"]
run = '''
	shell 'drag "$1"' --confirm
'''
desc = "Drag file(s) or folder(s)"

[[manager.prepend_keymap]]
on = ["H"]
run = 'hidden toggle'
desc = "Toggle hidden"
