[[manager.prepend_keymap]]
on   = [ "<C-d>" ]
exec = '''
	shell 'drag "$1"' --confirm
'''
desc = "Drag file(s) or folder(s)"


[[manager.prepend_keymap]]
on   = [ "H" ]
exec = '''hidden toggle'''
desc = "Toggle hidden"
